name: This project is deprecated
description: >
  Please file your issue in the Media3 issue tracker:
  https://github.com/androidx/media
labels: ["won't fix: infeasible"]
body:
- type: markdown
  attributes:
    value: |
      **This project is deprecated. Please do not file new issues in this repository. They will be closed with no response.**

      All new issues should be filed in the [Media3 issue tracker](https://github.com/androidx/media/issues/new/choose).

      We will continue to update and reply to existing issues in this repository, and will keep existing feature requests active.
- type: checkboxes
  attributes:
    label: This project is deprecated
    options:
      - label: I understand this project is deprecated, that I should file my issue in the [Media3 issue tracker](https://github.com/androidx/media/issues/new/choose) instead of here, and this issue will be closed with no response.
        required: true
